trigger:
- main

pool: Hitesh_Laptop_Pool

variables:
  serviceconnection : 'Hitesh_Service_Connection'


steps:
  - task: TerraformInstaller@1
    displayName: 'terraform install'  
    inputs:
      terraformVersion: 'latest'

  - task: TerraformTask@5
    displayName: 'terraform init'
    inputs:
      provider: 'azurerm'
      command: 'init'
      backendServiceArm: $(serviceconnection)
      backendAzureRmStorageAccountName: 'hiteshinitstorage'
      backendAzureRmContainerName: 'hiteshinitcontainer'
      backendAzureRmKey: 'terraform.tfstate'

  - task: TerraformTask@5
    displayName: 'terraform plan'
    inputs:
      provider: 'azurerm'
      command: 'plan'
      environmentServiceNameAzureRM: $(serviceconnection)

  - task: TerraformTask@5
    displayName: 'terraform apply'
    inputs:
      provider: 'azurerm'
      command: 'apply'
      environmentServiceNameAzureRM: $(serviceconnection)
